<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AskAny</AssemblyName>
    <RootNamespace>AskAny</RootNamespace>
    <ApplicationIcon>Assets\AskAny.ico</ApplicationIcon>
    <Version>0.2.0</Version>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AskAny.ico" />
  </ItemGroup>

</Project>
